### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by tasket** [tasket/sparsebak#20]
Looking for a new, permanent name for what is currently called sparsebak.

Some current candidates I'm tossing around...

__delta-v__

__parq__

__exidi__

__distar__

**Comment by jpouellet** [comment]
No intent to bikeshed here, but what's wrong with sparsebak exactly? It's unique and descriptive...

**Comment by csriq** [comment]
backup incremental qubes:
- **backiq**
- **bakiq**
- **qibak**

**Comment by tasket** [comment]
`wyng` will be the new release name.
