### ISSUE TITLE
Assert bkchunksize

### ISSUE THREAD

**Issue by StevenLColeman42** [tasket/sparsebak#3]
$ sudo /sparsebak/sparsebak.py send --save-to sys-usb:/run/media/user/USBdrive/sparsebak

I was attempting to "send" all my VM's private sections to a drive mounted on sys-usb, and I seem to have run into a problem with one particular AppVM. When it got to my vm-vault-private it printed:

> Delta map not finalized for **vm-vault-private** ...recovering.

and a few seconds later this exception:

> Processing Volume : **vm-vault-private**
> Updating block change map: Traceback (most recent call last):
>    File "/sparsebak/sparsebak.py", line 1008, in <module>
>       monitor_send(options.volumes, monitor_only=False)
>    File "/sparsebak/sparsebak.py", line 543, in monitor_send
>       = update_delta_digest()
>    File "/sparsebak/sparsebak.py", line 307, in update_delta_digest
>     assert bkchunksize >= (bs*dblocksize) and bkchunksize % (bs*dblocksize) == 0
> AssertionError

All the other AppVM's appeared to be processed/snapshot'ed Ok, but since there was this one fatal exception the backup obviously did not complete. I'm not sure what the complaint is with the blocksize because the AppVM runs fine and with no errors that I can see in the log file.

**Comment by tasket** [comment]
@StevenLColeman42 Thanks for the feedback.

First issue is the command line args: `--save-to` is only used for `receive` so here its being ignored (obviously it will help to have the program notify the user about such things in the future). The destination info is coming from the ini file. The appropriate command would be `sudo sparsebak.py send`.

---

The error appears to be from a bug in the way a brand new archive set is initialized... looking into it now.

**Comment by StevenLColeman42** [comment]
Here is the output messages from the new script:

Processing Volume : vm-vault-private
Updating block change map:  file         =
/tmp/sparsebak/delta.vm-vault-private
bkchunksize = 131072
dblocksize    = 4096
bs               = 512
Updating block change map: Traceback (most recent call last):
    File "/sparsebak/sparsebak.py", line 1016, in <module>
       monitor_send(options.volumes, monitor_only=False)
    File "/sparsebak/sparsebak.py", line 551, in monitor_send
       = update_delta_digest()
    File "/sparsebak/sparsebak.py", line 314, in update_delta_digest
     assert bkchunksize >= (bs*dblocksize) and bkchunksize %
(bs*dblocksize) == 0
AssertionError

**Comment by tasket** [comment]
@StevenLColeman42 I pushed a fix to https://github.com/tasket/sparsebak/tree/new

**Comment by StevenLColeman42** [comment]
update using the version from git branch new2:

...
> Processing Volume : vm-vault-private
> Updating block change map: 27262976 changed, 0 discarded.
> Backing up to qubes://sys-usbDATA 
>   100%   1025 x00000000401e0000 ______
> Traceback (most recent call last):
>   File "/sparsebak/sparsebak.py", line 1020, in <module>
>     monitor_send(options.volumes, monitor_only=False)
>   File "/sparsebak/sparsebak.py", line 557, in monitor_send
>     = send_volume(send_all = datavol in newvols)
>   File "/sparsebak/sparsebak.py", line 474, in send_volume
>     print("previous =", "none" if send_all else sessions[-1], file=f)
> IndexError: list index out of range

**Comment by tasket** [comment]
@StevenLColeman42 OK, this is a new bug and I pushed a possible fix to https://github.com/tasket/sparsebak/tree/new3

If there is a continued problem it would help to know what S_* session dirs are in vm-vault-private and whether there is a vm-vault-private.deltamap file.

**Comment by StevenLColeman42** [comment]
Looks like the patch in new3 did the trick. the vm-vault-private successfully backed up for the first time. 

Thanks!

**Comment by tasket** [comment]
Good to hear! As always, your feedback is appreciated.

There's also another update in new3, which I may tag as alpha4 tomorrow.
