### ISSUE TITLE
beta1 : restores QubesOS volume and not the config+metadata

### ISSUE THREAD

**Issue by tlaurion** [tasket/sparsebak#40]
Sorry if this is duplicate. Just wanted to make sure an issue was tracking missing feature talked about [here](https://github.com/tasket/sparsebak/issues/38#issuecomment-512078500)

**Comment by tasket** [comment]
If you're talking about _archive_ metadata, then its basically issue #38. 

If its _Qubes VM_ metadata (settings), then its issue #18.
