### ISSUE TITLE
Restoring backup when source host is down

### ISSUE THREAD

**Issue by gangamstyle** [tasket/sparsebak#44]
Let's suppose that source host is down and we want to restore volume data. How this can be done ? Host is different.
I have tried this:
sparsebak arch-init --source=dummy/nothing --destination=internal:/path/to/backup

but 
sparseback receive my-precious-volume --save-to=internal:./myfile.img
fails with
Destination not ready to receive commands.
I tried:
sparsebak add my-precious-volume
but that does not help

**Comment by gangamstyle** [comment]
I have mounted /path/to/backup readonly

**Comment by gangamstyle** [comment]
I have succeeded after reading @38 and removing "touch archive.dat" inside sparsebak.py
Please add --verbose option to see the magic.

**Comment by tasket** [comment]
Implemented with commit 8fd222f
