### ISSUE TITLE
"chunk size" error after successful initial backup

### ISSUE THREAD

**Issue by taradiddles** [tasket/sparsebak#5]
`/sparsebak/sparsebak.ini`:

~~~
[var]
vgname = qubes_dom0
poolname = pool00
destvm = qubes://work
destmountpoint = /home/user/mntenc-spbak
destdir = backups

[volumes]
vm-cftest-private = enable
~~~

Notes:

- `cftest` is a standaloneVM that I use for booting compact flash images from embedded routers. **I don't think I've ever written anything to the private volume - that could very well be the issue here.**
- `mntenc-spbak` is an ext4 fs on a luks volume on a file from an nfs share

Initial backup of the VM works:

`sudo /usr/local/bin/sparsebak.py send`:

> Configured Volumes:
>   vm-cftest-private
> 
> Starting backup session S_20181211-211105
> Preparing snapshots...
>   Initial snapshot created for vm-cftest-private
>   Current snapshot created: vm-cftest-private.tock
> 
> Scanning volume metadata...
> 
> Processing Volume : vm-cftest-private
> Backing up to VM work
>   100%   2047 x000000007ffe0000  DATA 
>   161 bytes sent.
> Rotating snapshots for vm-cftest-private
> 
> Done.

The backup is then properly shown:

`sudo /usr/local/bin/sparsebak.py list vm-cftest-private`

> Configured Volumes:
>   vm-cftest-private
> 
> Sessions for volume vm-cftest-private :
>   20181211-161151
> 
> Done.

... as are files in the `work` VM:

`ls -1 mntenc-spbak/backups/sparsebak/qubes_dom0%pool00/vm-cftest-private/S_20181211-161151/`

> 000000000
> 000000001
> 000000002
> 000000003
> 000000004
> 000000005
> 000000006
> 000000007
> info
> manifest

But then, subsequent backups fail:

`sudo /usr/local/bin/sparsebak.py send`:

> Configured Volumes:
>   vm-cftest-private
> 
> Starting backup session S_20181211-211316
> Preparing snapshots...
>   Delta map not finalized for vm-cftest-private ...recovering.
>   Current snapshot created: vm-cftest-private.tock
> 
> Scanning volume metadata...
> Acquiring LVM delta info.
> 
> Processing Volume : vm-cftest-private
> Updating block change map: file         = /tmp/sparsebak/delta.vm-cftest-private
> bkchunksize = 131072
> dblocksize  = 512
> bs          = 512
> Traceback (most recent call last):
>   File "/usr//local/bin/sparsebak.py", line 1016, in <module>
>     monitor_send(options.volumes, monitor_only=False)
>   File "/usr//local/bin/sparsebak.py", line 551, in monitor_send
>     = update_delta_digest()
>   File "/usr//local/bin/sparsebak.py", line 314, in update_delta_digest
>     raise ValueError("Chunk size error")
> ValueError: Chunk size error

EDIT: the issue is reproducible after "resetting" everything (rm  /sparsebak/... + lvremove the tick/tock volumes in dom0, and rm mntenc-bak/... in the dest VM)

EDIT2: forgot to add that `sparsebak.py monitor` gives the same error (only difference is the action - line 1013, `monitor_send(monitory_only=True`)

**Comment by tasket** [comment]
Thanks for the details. The error was triggered by the LVM tools setting `dblocksize` to 512 - I've only ever seen it as 256. LVM documentation doesn't elaborate on the range of values so I've asked their devs about it.

**Comment by taradiddles** [comment]
OK ! - let me know if/when you want me to test further.
Again, thanks for the time you're putting into this.

**Comment by tasket** [comment]
@taradiddles I pushed a fix to https://github.com/tasket/sparsebak/tree/new

The guard condition I added to alpha1 was contrary to my design intent (back in August), which I'd forgotten was to allow for different lvm dblocksizes.

**Comment by taradiddles** [comment]
That did it - no more error message.

Until now I've played only with general usage stuff, I haven't even tried to restore a backup. I'll try to do more extensive tests when time allows...

**Comment by tasket** [comment]
That sounds great. Thanks again!
